title: "Ellen Boven"
author: "Ellen Boven"
description: "Erasmus Medical Centre"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://github.com/BovenEllen/BovenEllen.github.io/blob/881b86bd1e2332f20719f583c7428affb1ca5ed4/CV.pdf", title: "CV"}#, icon: home}
  - {file: "README.md", title: "About me"}#, icon: address-card}
  - {file: "index.md", title: "Science"}#, icon: address-card}
  - {file: "index.html", title: "Life"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:e.boven@erasmusmc.nl"}
  - {title: Github, icon: github, url: "https://github.com/BovenEllen"}
  - {title: Google Scholar, icon: googlescholar, url: "https://scholar.google.de/citations?user=hiGq-U0AAAAJ&hl=nl"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
